framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true
    csrf_protection:
        enabled: true

    # Configuration des traductions
    default_locale: 'fr'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['fr']
        enabled: true

    # Activer les sessions
    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            handler_id: session.handler.native_file
            storage_id: session.storage.native
            cookie_secure: auto
            cookie_samesite: lax