knp_snappy:
    pdf:
        enabled: true
        binary: '"C:\wkhtmltopdf\bin\wkhtmltopdf"'
        options:
            lowquality: true
            load-error-handling: ignore
    image:
        enabled: false