security:
    password_hashers:
        App\Entity\Membre:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Membre
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_auth
                check_path: login_check
                default_target_path: admin_dashboard
                username_parameter: "login_form[email]"
                password_parameter: "login_form[motDePasse]"
            logout:
                path: app_logout
                target: app_auth
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: PUBLIC_ACCESS }