security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\Membre:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Membre
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_auth
                check_path: app_auth
            logout:
                path: app_logout
                target: app_auth
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_AGENT, ROLE_MEMBRE]
        ROLE_AGENT: [ROLE_MEMBRE]
        ROLE_MEMBRE: [ROLE_USER]

when@test:
    security:
        password_hashers:
            App\Entity\Membre:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10