controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

connect_google:
    path: /connect/google
    controller: App\Controller\GoogleAuthController::connect

connect_google_check:
    path: /connect/google/check
    controller: App\Controller\GoogleAuthController::connectCheck
