parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'
    brevo_api_key: '%env(BREVO_API_KEY)%'
    wkhtmltopdf_path: '%env(resolve:WKHTMLTOPDF_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Knp\Snappy\Pdf:
        arguments:
            $binary: '%wkhtmltopdf_path%'
            $options:
                enable-local-file-access: true
                enable-javascript: true
                minimum-font-size: 12
                image-dpi: 300
                image-quality: 94

    App\Repository\TypepackRepository:
        arguments:
            $registry: '@doctrine'
            $entityClass: 'App\Entity\Typepack'

    App\Service\AiResponseGenerator:
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $logger: '@monolog.logger'
            $apiKey: '%env(GEMINI_API_KEY)%'
            $apiEndpoint: '%env(GEMINI_API_ENDPOINT)%'

    App\Controller\Users\ChatAiController:
        arguments:
            $geminiApiKey: '%env(GOOGLE_GEMINI_API_KEY)%'
