parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'
    brevo_api_key: '%env(BREVO_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Repository\TypepackRepository:
        arguments:
            $registry: '@doctrine'
            $entityClass: 'App\Entity\Typepack'
