parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'
    brevo_api_key: '%env(BREVO_API_KEY)%'
    twilio_account_sid: '%env(TWILIO_ACCOUNT_SID)%'
    twilio_auth_token: '%env(TWILIO_AUTH_TOKEN)%'
    twilio_phone_number: '%env(TWILIO_PHONE_NUMBER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Knp\Snappy\Pdf:
        arguments:
            $binary: '%kernel.project_dir%/bin/wkhtmltopdf'
            $options: []

    App\Repository\TypepackRepository:
        arguments:
            $registry: '@doctrine'
            $entityClass: 'App\Entity\Typepack'

    App\Service\AiResponseGenerator:
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $logger: '@monolog.logger'
            $apiKey: '%env(GEMINI_API_KEY)%'
            $apiEndpoint: '%env(GEMINI_API_ENDPOINT)%'

    App\Controller\Users\ChatAiController:
        arguments:
            $geminiApiKey: '%env(GOOGLE_GEMINI_API_KEY)%'

    App\Controller\Users\UserReservationsController:
        arguments:
            $twilioAccountSid: '%twilio_account_sid%'
            $twilioAuthToken: '%twilio_auth_token%'
            $twilioPhoneNumber: '%twilio_phone_number%'
            $logger: '@logger'